### ISSUE TITLE
discuss: how to handle multiple answers in backend

### ISSUE THREAD

**Issue by theo333** [pilot-js/seedo#31]
`/api/userchallenges/challenge/:challengeId` route

How are we going to handle multiple answers since we said we would allow them?

In `post` route, do we first have to check if there is an answer, then do something differently if there is one?

In `get` route, how to decide which answer to retrieve?

**Comment by hgranthorner** [comment]
We can think about this in terms of the different http verbs.

Get: either get one, get active (submission === false) or get all. For get one, we could pass the id of that userchallenge row back to the server. For get all, we could just findall where userid = the user id and challengeid = the challenge id.

For getting the active userchallenge, there are three cases to consider:
1. There are no userchallenges - create an active userchallenge for that challenge and return it.
2. There are userchallenges, but no "unsubmitted" userchallenge - create an active userchallenge for that challenge and return it.
3. There is an unsubmitted userchallenge - find the unsubmitted userchallenge and return it.

It would be best to handle this case with a class method ("getWorkingSolution" or something along those lines) so that the logic would be contained on the model.
